name: CI-Inspection with SonarQube
on:
  push:
    branches: 
      - main
  pull_request_target:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  build:
    name: Build and analyze
    runs-on: ubuntu-latest
    steps:

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'zulu' # Alternative distribution options are available.
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
  
      # Run checking for Unity license
      - name: Check for presence of UNITY_LICENSE secret
        shell: bash
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        run: |
          if [[ -n "$UNITY_LICENSE" ]]; then
            echo "SUCCESS: UNITY_LICENSE secret was found."
          else
            echo "ERROR: UNITY_LICENSE secret is MISSING or empty."
            exit 1
          fi
  
      # REPLACED a faulty action with a direct Docker command for 100% control
      - name: Generate C# Solution File via Docker
        shell: bash
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        run: |
          docker run \
            -e UNITY_LICENSE \
            -v "${{ github.workspace }}":/project \
            -w /project \
            unityci/editor:ubuntu-2022.3.20f1-base \
            /opt/unity/Editor/Unity \
              -batchmode \
              -nographics \
              -executeMethod UnityEditor.SyncVS.SyncSolution \
              -quit \
              -logFile /dev/stdout
      
      - name: Cache SonarQube Cloud packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Cache SonarQube Cloud scanner
        id: cache-sonar-scanner
        uses: actions/cache@v4
        with:
          path: ./.sonar/scanner
          key: ${{ runner.os }}-sonar-scanner
          restore-keys: ${{ runner.os }}-sonar-scanner

      - name: Install SonarQube Cloud scanner
        if: steps.cache-sonar-scanner.outputs.cache-hit != 'true'
        shell: bash
        run: |
          mkdir -p ./.sonar/scanner
          dotnet tool install dotnet-sonarscanner --tool-path ./.sonar/scanner

      - name: Build and analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        shell: bash
        run: |
          ./.sonar/scanner/dotnet-sonarscanner begin /k:"kalpratama_GameZombrrrt" /o:"kalpratama" /d:sonar.login="${{ secrets.SONAR_TOKEN }}" /d:sonar.host.url="https://sonarcloud.io"
          dotnet build GameZombrrrt.sln 
          ./.sonar/scanner/dotnet-sonarscanner end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"
