name: CI - SonarCloud Analysis

on:
  push:
    branches: 
      - main
  pull_request_target:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  build-and-analyze:
    name: Build and Analyze
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Pull Request Code
        uses: actions/checkout@v4
        with:
          # This is critical for pull_request_target to analyze the correct code
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'zulu'

      - name: Set up .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '6.0.x'

      - name: Install .NET Framework Dependencies
        # This step fixes the "reference assemblies for .NETFramework,Version=v4.7.1 were not found" error
        run: sudo apt-get update && sudo apt-get install -y mono-devel

      - name: Install SonarScanner Globally
        shell: bash
        # This step uses "cd /tmp" to avoid conflicts with project files in the workspace
        run: |
          cd /tmp
          dotnet tool install --global dotnet-sonarscanner

      - name: Execute SonarCloud Analysis
        env:
          # GITHUB_TOKEN is automatically provided by GitHub
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        shell: bash
        run: |
          dotnet-sonarscanner begin /k:"kalpratama_GameZombrrrt" /o:"kalpratama" /d:sonar.login="${{ secrets.SONAR_TOKEN }}" /d:sonar.host.url="https://sonarcloud.io"
          
          dotnet build GameZombrrrt.sln
          
          dotnet-sonarscanner end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"
