name: CI - SonarCloud Analysis

on:
  push:
    branches: 
      - main
  pull_request_target:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  build-and-analyze:
    name: Build and Analyze
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'zulu'

      - name: Install SonarScanner
        run: dotnet tool install --global dotnet-sonarscanner --version 5.15.0
      
      - name: Start SonarScanner
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          dotnet-sonarscanner begin /k:"kalpratama_GameZombrrrt" /o:"kalpratama" /d:sonar.login="${{ secrets.SONAR_TOKEN }}" /d:sonar.host.url="https://sonarcloud.io"

      - name: Build Project inside Unity Environment
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        run: |
          docker run \
            -e UNITY_LICENSE \
            -v "${{ github.workspace }}":/project \
            -w /project \
            unityci/editor:2022-lts \
            /opt/unity/Editor/Unity \
              -batchmode \
              -nographics \
              -buildTarget StandaloneLinux64 \
              -projectPath . \
              -logFile /dev/stdout

      - name: End SonarScanner
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          dotnet-sonarscanner end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"
