name: CI - SonarCloud Analysis

on:
  push:
    branches: 
      - main
  pull_request_target:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  build-and-analyze:
    name: Build and Analyze
    # WAJIB: Pastikan baris ini tertulis 'windows-latest' dan indentasinya benar.
    runs-on: windows-latest
    steps:

      - name: Checkout Pull Request Code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'zulu'

      - name: Set up .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '6.0.x'

      # Langkah instalasi mono-devel sudah dihapus karena kita di Windows

      - name: Install SonarScanner Globally
        # PENTING: Gunakan 'pwsh' (PowerShell) sebagai shell di Windows
        shell: pwsh
        run: dotnet tool install --global dotnet-sonarscanner

      - name: Execute SonarCloud Analysis
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        # PENTING: Gunakan 'pwsh' juga di sini
        shell: pwsh
        run: |
          dotnet-sonarscanner begin /k:"kalpratama_GameZombrrrt" /o:"kalpratama" /d:sonar.login="${{ secrets.SONAR_TOKEN }}" /d:sonar.host.url="https://sonarcloud.io"
          
          # Perintah ini yang membutuhkan .NET Framework dan harus berjalan di Windows
          dotnet build GameZombrrrt.sln
          
          dotnet-sonarscanner end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"
